baseURL = '/'
languageCode = 'en-us'
title = 'Hello! I am Didit - an Engineer'

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"
	
[caches]
  [caches.images]
    dir = ':cacheDir/images'