baseURL = 'https://ichromanrd.dev'
languageCode = 'en-us'
title = 'My Sanctuary'

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"
	
[caches]
  [caches.images]
    dir = ':cacheDir/images'